# Jekyll configuration
name: PNNL-Comp-Mass-Spec
description: Software downloads category listing for the PNNL-Comp-Mass-Spec GitHub organization
url: https://pnnl-comp-mass-spec.github.io/

# Google Analytics
google_analytics: G-LXXKP1N66C
